-- ============================================================
-- PROJETO : Monitoramento de Indisponibilidade
-- SCHEMA  : USU_INDISPONIBILIDADE
-- GERADO  : 20/07/2026 | VERSAO: 1.1
-- SGBD    : Oracle 19c
-- TABLESPACE DADOS  : USU_INDISPONIBILIDADE_D
-- TABLESPACE INDICES: USU_INDISPONIBILIDADE_I
-- ============================================================
-- AUDITORIA (obrigatoria em toda tabela de negocio):
--   NUM_CPF_USUARIO_CRIACAO      - CPF de quem criou      (NOT NULL)
--   NUM_CPF_USUARIO_ATUALIZACAO  - CPF de quem atualizou
--   NUM_CPF_USUARIO_REMOCAO      - CPF de quem removeu
--   DAT_CRIACAO                  - data de criacao        (NOT NULL)
--   DAT_ATUALIZACAO              - data da ultima atualizacao
--   DAT_REMOCAO                  - data de remocao logica (soft delete)
-- Excecao: LOG_SERVICO_MONITORADO (tabela append-only de auditoria).
-- ------------------------------------------------------------
-- Ordem de criacao respeita as dependencias de FK:
--   1. SERVICO_MONITORADO
--   2. LOG_SERVICO_MONITORADO
--   3. HIERARQUIA_SERVICO
--   4. INDISPONIBILIDADE
--   5. RELATORIO
--   6. RELATORIO_SERVICO
-- ============================================================


-- ============================================================
-- TABELA: SERVICO_MONITORADO
-- ============================================================
CREATE TABLE SERVICO_MONITORADO (
    ID_SERVICO                   NUMBER(10)     NOT NULL,
    COD_SISTEMA                  VARCHAR2(50)   NOT NULL,
    SGL_SERVICO                  VARCHAR2(20)   NOT NULL,
    NOM_SERVICO                  VARCHAR2(150)  NOT NULL,
    DSC_URL_HEALTHCHECK          VARCHAR2(500)  NOT NULL,
    SGL_STATUS                   CHAR(1)        DEFAULT 'A' NOT NULL,
    DAT_INCLUSAO                 DATE           DEFAULT SYSDATE NOT NULL,
    NUM_CPF_USUARIO_CRIACAO      NUMBER(11)     NOT NULL,
    NUM_CPF_USUARIO_ATUALIZACAO  NUMBER(11),
    NUM_CPF_USUARIO_REMOCAO      NUMBER(11),
    DAT_CRIACAO                  DATE           DEFAULT SYSDATE NOT NULL,
    DAT_ATUALIZACAO              DATE,
    DAT_REMOCAO                  DATE,
    CONSTRAINT PK_SERVICO_MONITORADO     PRIMARY KEY (ID_SERVICO),
    CONSTRAINT UK_SERVICO_MONITORADO     UNIQUE (COD_SISTEMA),
    CONSTRAINT CK_SERVICO_MONITORADO_001 CHECK (SGL_STATUS IN ('A','I','R'))
) TABLESPACE USU_INDISPONIBILIDADE_D;

COMMENT ON TABLE  SERVICO_MONITORADO                             IS 'Servico/sistema sob monitoramento de healthcheck';
COMMENT ON COLUMN SERVICO_MONITORADO.ID_SERVICO                  IS 'Identificador unico do servico';
COMMENT ON COLUMN SERVICO_MONITORADO.COD_SISTEMA                 IS 'Codigo do sistema no inventario do Portal de Servicos';
COMMENT ON COLUMN SERVICO_MONITORADO.SGL_SERVICO                 IS 'Sigla do servico (ex.: E-TCE)';
COMMENT ON COLUMN SERVICO_MONITORADO.NOM_SERVICO                 IS 'Nome por extenso do sistema';
COMMENT ON COLUMN SERVICO_MONITORADO.DSC_URL_HEALTHCHECK         IS 'URL do endpoint de healthcheck';
COMMENT ON COLUMN SERVICO_MONITORADO.SGL_STATUS                  IS 'A=Ativo, I=Inativo, R=Removido';
COMMENT ON COLUMN SERVICO_MONITORADO.DAT_INCLUSAO                IS 'Data de inclusao no monitoramento';
COMMENT ON COLUMN SERVICO_MONITORADO.NUM_CPF_USUARIO_CRIACAO     IS 'CPF do usuario que criou o registro';
COMMENT ON COLUMN SERVICO_MONITORADO.NUM_CPF_USUARIO_ATUALIZACAO IS 'CPF do usuario que atualizou o registro';
COMMENT ON COLUMN SERVICO_MONITORADO.NUM_CPF_USUARIO_REMOCAO     IS 'CPF do usuario que removeu o registro';
COMMENT ON COLUMN SERVICO_MONITORADO.DAT_CRIACAO                 IS 'Data de criacao do registro';
COMMENT ON COLUMN SERVICO_MONITORADO.DAT_ATUALIZACAO             IS 'Data da ultima atualizacao';
COMMENT ON COLUMN SERVICO_MONITORADO.DAT_REMOCAO                 IS 'Data de remocao logica (soft delete)';

CREATE SEQUENCE SQ_SERVICO_MONITORADO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- ============================================================
-- TABELA: LOG_SERVICO_MONITORADO  (auditoria append-only)
-- ============================================================
CREATE TABLE LOG_SERVICO_MONITORADO (
    ID_LOG        NUMBER(12)  NOT NULL,
    ID_SERVICO    NUMBER(10)  NOT NULL,
    SGL_OPERACAO  CHAR(1)     NOT NULL,
    DAT_OPERACAO  DATE        DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_LOG_SERVICO_MONITORADO     PRIMARY KEY (ID_LOG),
    CONSTRAINT CK_LOG_SERVICO_MONITORAD_001  CHECK (SGL_OPERACAO IN ('I','U','D'))
) TABLESPACE USU_INDISPONIBILIDADE_D;

COMMENT ON TABLE  LOG_SERVICO_MONITORADO              IS 'Auditoria (append-only) de operacoes sobre servicos monitorados';
COMMENT ON COLUMN LOG_SERVICO_MONITORADO.ID_LOG       IS 'Identificador unico do log';
COMMENT ON COLUMN LOG_SERVICO_MONITORADO.ID_SERVICO   IS 'Servico afetado pela operacao';
COMMENT ON COLUMN LOG_SERVICO_MONITORADO.SGL_OPERACAO IS 'I=Insert, U=Update, D=Delete';
COMMENT ON COLUMN LOG_SERVICO_MONITORADO.DAT_OPERACAO IS 'Data/hora da operacao';

CREATE SEQUENCE SQ_LOG_SERVICO_MONITORADO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


-- ============================================================
-- TABELA: HIERARQUIA_SERVICO  (associativa N:M autorrelacionada)
-- ============================================================
CREATE TABLE HIERARQUIA_SERVICO (
    ID_HIERARQUIA                NUMBER(10)  NOT NULL,
    ID_SERVICO_FILHO             NUMBER(10)  NOT NULL,
    ID_SERVICO_PAI               NUMBER(10)  NOT NULL,
    IND_ATIVO                    CHAR(1)     DEFAULT 'S' NOT NULL,
    NUM_CPF_USUARIO_CRIACAO      NUMBER(11)  NOT NULL,
    NUM_CPF_USUARIO_ATUALIZACAO  NUMBER(11),
    NUM_CPF_USUARIO_REMOCAO      NUMBER(11),
    DAT_CRIACAO                  DATE        DEFAULT SYSDATE NOT NULL,
    DAT_ATUALIZACAO              DATE,
    DAT_REMOCAO                  DATE,
    CONSTRAINT PK_HIERARQUIA_SERVICO     PRIMARY KEY (ID_HIERARQUIA),
    CONSTRAINT UK_HIERARQUIA_SERVICO     UNIQUE (ID_SERVICO_FILHO, ID_SERVICO_PAI),
    CONSTRAINT CK_HIERARQUIA_SERVICO_001 CHECK (ID_SERVICO_FILHO <> ID_SERVICO_PAI),
    CONSTRAINT CK_HIERARQUIA_SERVICO_002 CHECK (IND_ATIVO IN ('S','N'))
) TABLESPACE USU_INDISPONIBILIDADE_D;

COMMENT ON TABLE  HIERARQUIA_SERVICO                             IS 'Vinculo hierarquico pai-filho entre servicos monitorados';
COMMENT ON COLUMN HIERARQUIA_SERVICO.ID_HIERARQUIA               IS 'Identificador unico do vinculo';
COMMENT ON COLUMN HIERARQUIA_SERVICO.ID_SERVICO_FILHO           IS 'FK para SERVICO_MONITORADO (servico filho)';
COMMENT ON COLUMN HIERARQUIA_SERVICO.ID_SERVICO_PAI             IS 'FK para SERVICO_MONITORADO (servico pai)';
COMMENT ON COLUMN HIERARQUIA_SERVICO.IND_ATIVO                  IS 'S=vinculo vigente, N=vinculo suspenso (servico inativado)';
COMMENT ON COLUMN HIERARQUIA_SERVICO.NUM_CPF_USUARIO_CRIACAO     IS 'CPF do usuario que criou o registro';
COMMENT ON COLUMN HIERARQUIA_SERVICO.NUM_CPF_USUARIO_ATUALIZACAO IS 'CPF do usuario que atualizou o registro';
COMMENT ON COLUMN HIERARQUIA_SERVICO.NUM_CPF_USUARIO_REMOCAO     IS 'CPF do usuario que removeu o registro';
COMMENT ON COLUMN HIERARQUIA_SERVICO.DAT_CRIACAO                 IS 'Data de criacao do vinculo';
COMMENT ON COLUMN HIERARQUIA_SERVICO.DAT_ATUALIZACAO             IS 'Data da ultima atualizacao';
COMMENT ON COLUMN HIERARQUIA_SERVICO.DAT_REMOCAO                 IS 'Data de remocao logica (soft delete)';

CREATE SEQUENCE SQ_HIERARQUIA_SERVICO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IX_FK_HIERARQUIA_SERVICO_01 ON HIERARQUIA_SERVICO (ID_SERVICO_FILHO) TABLESPACE USU_INDISPONIBILIDADE_I;
CREATE INDEX IX_FK_HIERARQUIA_SERVICO_02 ON HIERARQUIA_SERVICO (ID_SERVICO_PAI)   TABLESPACE USU_INDISPONIBILIDADE_I;

ALTER TABLE HIERARQUIA_SERVICO ADD CONSTRAINT FK_SERVICO_MONITORADO_01
    FOREIGN KEY (ID_SERVICO_FILHO) REFERENCES SERVICO_MONITORADO (ID_SERVICO);
ALTER TABLE HIERARQUIA_SERVICO ADD CONSTRAINT FK_SERVICO_MONITORADO_02
    FOREIGN KEY (ID_SERVICO_PAI)   REFERENCES SERVICO_MONITORADO (ID_SERVICO);


-- ============================================================
-- TABELA: INDISPONIBILIDADE  (periodos confirmados)
-- ============================================================
CREATE TABLE INDISPONIBILIDADE (
    ID_INDISPONIBILIDADE         NUMBER(12)  NOT NULL,
    ID_SERVICO                   NUMBER(10)  NOT NULL,
    DAT_INICIO                   DATE        NOT NULL,
    DAT_FIM                      DATE,
    NUM_DURACAO_MIN              NUMBER(10),
    NUM_CPF_USUARIO_CRIACAO      NUMBER(11)  NOT NULL,
    NUM_CPF_USUARIO_ATUALIZACAO  NUMBER(11),
    NUM_CPF_USUARIO_REMOCAO      NUMBER(11),
    DAT_CRIACAO                  DATE        DEFAULT SYSDATE NOT NULL,
    DAT_ATUALIZACAO              DATE,
    DAT_REMOCAO                  DATE,
    CONSTRAINT PK_INDISPONIBILIDADE     PRIMARY KEY (ID_INDISPONIBILIDADE),
    CONSTRAINT CK_INDISPONIBILIDADE_001 CHECK (DAT_FIM IS NULL OR DAT_FIM >= DAT_INICIO)
) TABLESPACE USU_INDISPONIBILIDADE_D;

COMMENT ON TABLE  INDISPONIBILIDADE                             IS 'Periodo confirmado de indisponibilidade de um servico';
COMMENT ON COLUMN INDISPONIBILIDADE.ID_INDISPONIBILIDADE        IS 'Identificador unico do periodo';
COMMENT ON COLUMN INDISPONIBILIDADE.ID_SERVICO                  IS 'FK para SERVICO_MONITORADO';
COMMENT ON COLUMN INDISPONIBILIDADE.DAT_INICIO                  IS 'Inicio do periodo (horario da primeira falha)';
COMMENT ON COLUMN INDISPONIBILIDADE.DAT_FIM                     IS 'Fim do periodo; nulo se em andamento';
COMMENT ON COLUMN INDISPONIBILIDADE.NUM_DURACAO_MIN             IS 'Duracao em minutos, calculada no fechamento';
COMMENT ON COLUMN INDISPONIBILIDADE.NUM_CPF_USUARIO_CRIACAO     IS 'CPF do usuario/servico que criou o registro';
COMMENT ON COLUMN INDISPONIBILIDADE.NUM_CPF_USUARIO_ATUALIZACAO IS 'CPF do usuario/servico que atualizou o registro';
COMMENT ON COLUMN INDISPONIBILIDADE.NUM_CPF_USUARIO_REMOCAO     IS 'CPF do usuario que removeu o registro';
COMMENT ON COLUMN INDISPONIBILIDADE.DAT_CRIACAO                 IS 'Data de criacao do registro';
COMMENT ON COLUMN INDISPONIBILIDADE.DAT_ATUALIZACAO             IS 'Data da ultima atualizacao';
COMMENT ON COLUMN INDISPONIBILIDADE.DAT_REMOCAO                 IS 'Data de remocao logica (soft delete)';

CREATE SEQUENCE SQ_INDISPONIBILIDADE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IX_FK_INDISPONIBILIDADE_01 ON INDISPONIBILIDADE (ID_SERVICO)              TABLESPACE USU_INDISPONIBILIDADE_I;
CREATE INDEX IX_INDISPONIBILIDADE_01    ON INDISPONIBILIDADE (DAT_INICIO, ID_SERVICO)  TABLESPACE USU_INDISPONIBILIDADE_I;

ALTER TABLE INDISPONIBILIDADE ADD CONSTRAINT FK_SERVICO_MONITORADO_03
    FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO_MONITORADO (ID_SERVICO);


-- ============================================================
-- TABELA: RELATORIO
-- ============================================================
CREATE TABLE RELATORIO (
    ID_RELATORIO                 NUMBER(10)    NOT NULL,
    DAT_REFERENCIA               DATE          NOT NULL,
    SGL_TIPO                     CHAR(1)       NOT NULL,
    COD_VERIFICADOR              VARCHAR2(50),
    NUM_LIMIAR_MIN               NUMBER(5),
    IND_PARCIAL                  CHAR(1)       DEFAULT 'N' NOT NULL,
    SGL_STATUS                   CHAR(1)       DEFAULT 'C' NOT NULL,
    DAT_GERACAO                  DATE          DEFAULT SYSDATE NOT NULL,
    NUM_CPF_USUARIO_CRIACAO      NUMBER(11)    NOT NULL,
    NUM_CPF_USUARIO_ATUALIZACAO  NUMBER(11),
    NUM_CPF_USUARIO_REMOCAO      NUMBER(11),
    DAT_CRIACAO                  DATE          DEFAULT SYSDATE NOT NULL,
    DAT_ATUALIZACAO              DATE,
    DAT_REMOCAO                  DATE,
    CONSTRAINT PK_RELATORIO     PRIMARY KEY (ID_RELATORIO),
    CONSTRAINT UK_RELATORIO     UNIQUE (COD_VERIFICADOR),
    CONSTRAINT CK_RELATORIO_001 CHECK (SGL_TIPO IN ('L','A')),
    CONSTRAINT CK_RELATORIO_002 CHECK (IND_PARCIAL IN ('S','N')),
    CONSTRAINT CK_RELATORIO_003 CHECK (SGL_STATUS IN ('C','P','E'))
) TABLESPACE USU_INDISPONIBILIDADE_D;

COMMENT ON TABLE  RELATORIO                             IS 'Relatorio diario gerado: L=por limiar (usuario), A=diario do administrador';
COMMENT ON COLUMN RELATORIO.ID_RELATORIO                IS 'Identificador unico do relatorio';
COMMENT ON COLUMN RELATORIO.DAT_REFERENCIA              IS 'Dia de referencia do relatorio';
COMMENT ON COLUMN RELATORIO.SGL_TIPO                    IS 'L=Por Limiar, A=Diario Administrador';
COMMENT ON COLUMN RELATORIO.COD_VERIFICADOR             IS 'Codigo verificador unico (apenas tipo L)';
COMMENT ON COLUMN RELATORIO.NUM_LIMIAR_MIN              IS 'Limiar aplicado em minutos - snapshot (apenas tipo L)';
COMMENT ON COLUMN RELATORIO.IND_PARCIAL                 IS 'S=parcial/em andamento, N=fechado';
COMMENT ON COLUMN RELATORIO.SGL_STATUS                  IS 'C=Concluido, P=Parcial, E=Erro';
COMMENT ON COLUMN RELATORIO.DAT_GERACAO                 IS 'Data/hora da geracao do relatorio';
COMMENT ON COLUMN RELATORIO.NUM_CPF_USUARIO_CRIACAO     IS 'CPF do usuario/servico que criou o registro';
COMMENT ON COLUMN RELATORIO.NUM_CPF_USUARIO_ATUALIZACAO IS 'CPF do usuario que atualizou o registro';
COMMENT ON COLUMN RELATORIO.NUM_CPF_USUARIO_REMOCAO     IS 'CPF do usuario que removeu o registro';
COMMENT ON COLUMN RELATORIO.DAT_CRIACAO                 IS 'Data de criacao do registro';
COMMENT ON COLUMN RELATORIO.DAT_ATUALIZACAO             IS 'Data da ultima atualizacao';
COMMENT ON COLUMN RELATORIO.DAT_REMOCAO                 IS 'Data de remocao logica (soft delete)';

CREATE SEQUENCE SQ_RELATORIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IX_RELATORIO_01 ON RELATORIO (DAT_REFERENCIA, SGL_TIPO) TABLESPACE USU_INDISPONIBILIDADE_I;


-- ============================================================
-- TABELA: RELATORIO_SERVICO  (associativa - snapshot de sistemas por relatorio)
-- ============================================================
CREATE TABLE RELATORIO_SERVICO (
    ID_RELATORIO_SERVICO         NUMBER(12)  NOT NULL,
    ID_RELATORIO                 NUMBER(10)  NOT NULL,
    ID_SERVICO                   NUMBER(10)  NOT NULL,
    NUM_TOTAL_MIN                NUMBER(10)  NOT NULL,
    NUM_CPF_USUARIO_CRIACAO      NUMBER(11)  NOT NULL,
    NUM_CPF_USUARIO_ATUALIZACAO  NUMBER(11),
    NUM_CPF_USUARIO_REMOCAO      NUMBER(11),
    DAT_CRIACAO                  DATE        DEFAULT SYSDATE NOT NULL,
    DAT_ATUALIZACAO              DATE,
    DAT_REMOCAO                  DATE,
    CONSTRAINT PK_RELATORIO_SERVICO PRIMARY KEY (ID_RELATORIO_SERVICO),
    CONSTRAINT UK_RELATORIO_SERVICO UNIQUE (ID_RELATORIO, ID_SERVICO)
) TABLESPACE USU_INDISPONIBILIDADE_D;

COMMENT ON TABLE  RELATORIO_SERVICO                             IS 'Sistemas incluidos em um relatorio com total acumulado do dia';
COMMENT ON COLUMN RELATORIO_SERVICO.ID_RELATORIO_SERVICO        IS 'Identificador unico';
COMMENT ON COLUMN RELATORIO_SERVICO.ID_RELATORIO               IS 'FK para RELATORIO';
COMMENT ON COLUMN RELATORIO_SERVICO.ID_SERVICO                 IS 'FK para SERVICO_MONITORADO';
COMMENT ON COLUMN RELATORIO_SERVICO.NUM_TOTAL_MIN              IS 'Total acumulado de indisponibilidade no dia (minutos)';
COMMENT ON COLUMN RELATORIO_SERVICO.NUM_CPF_USUARIO_CRIACAO     IS 'CPF do usuario/servico que criou o registro';
COMMENT ON COLUMN RELATORIO_SERVICO.NUM_CPF_USUARIO_ATUALIZACAO IS 'CPF do usuario que atualizou o registro';
COMMENT ON COLUMN RELATORIO_SERVICO.NUM_CPF_USUARIO_REMOCAO     IS 'CPF do usuario que removeu o registro';
COMMENT ON COLUMN RELATORIO_SERVICO.DAT_CRIACAO                 IS 'Data de criacao do registro';
COMMENT ON COLUMN RELATORIO_SERVICO.DAT_ATUALIZACAO             IS 'Data da ultima atualizacao';
COMMENT ON COLUMN RELATORIO_SERVICO.DAT_REMOCAO                 IS 'Data de remocao logica (soft delete)';

CREATE SEQUENCE SQ_RELATORIO_SERVICO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE INDEX IX_FK_RELATORIO_SERVICO_01 ON RELATORIO_SERVICO (ID_RELATORIO) TABLESPACE USU_INDISPONIBILIDADE_I;
CREATE INDEX IX_FK_RELATORIO_SERVICO_02 ON RELATORIO_SERVICO (ID_SERVICO)   TABLESPACE USU_INDISPONIBILIDADE_I;

ALTER TABLE RELATORIO_SERVICO ADD CONSTRAINT FK_RELATORIO
    FOREIGN KEY (ID_RELATORIO) REFERENCES RELATORIO (ID_RELATORIO);
ALTER TABLE RELATORIO_SERVICO ADD CONSTRAINT FK_SERVICO_MONITORADO_04
    FOREIGN KEY (ID_SERVICO)   REFERENCES SERVICO_MONITORADO (ID_SERVICO);


-- ============================================================
-- TRIGGER DE LOG: SERVICO_MONITORADO
-- ============================================================
CREATE OR REPLACE TRIGGER TG_A_IUD_SERVICO_MONITORADO
AFTER INSERT OR UPDATE OR DELETE ON SERVICO_MONITORADO
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO LOG_SERVICO_MONITORADO (ID_LOG, ID_SERVICO, SGL_OPERACAO, DAT_OPERACAO)
        VALUES (SQ_LOG_SERVICO_MONITORADO.NEXTVAL, :NEW.ID_SERVICO, 'I', SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO LOG_SERVICO_MONITORADO (ID_LOG, ID_SERVICO, SGL_OPERACAO, DAT_OPERACAO)
        VALUES (SQ_LOG_SERVICO_MONITORADO.NEXTVAL, :NEW.ID_SERVICO, 'U', SYSDATE);
    ELSIF DELETING THEN
        INSERT INTO LOG_SERVICO_MONITORADO (ID_LOG, ID_SERVICO, SGL_OPERACAO, DAT_OPERACAO)
        VALUES (SQ_LOG_SERVICO_MONITORADO.NEXTVAL, :OLD.ID_SERVICO, 'D', SYSDATE);
    END IF;
END;
/
